schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_label: 'macOS-10.15'
    base_image_name: 'clean-macOS-10.15-380Gb-runner'
    template_path: 'templates/macOS-10.15.json'
    target_datastore: 'ds-image'
