schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- template: image-generation.yml
  parameters:
    image_label: 'macOS High Sierra'
    base_image_name: 'clean-macOS-10.13.6-380Gb-SIPoff_runner'
    image_name: 'macOS-10.13'
    target_datastore: 'ds-image'
