jobs:
- job:
  pool: ci-agent-pool
  steps:
  - script: |
      ./images.CI/build-image.ps1 -ResourcesNamePrefix $(Build.BuildNumber) `
                        -ClientId $(CLIENT_ID) `
                        -ClientSecret $(CLIENT_SECRET) `
                        -Image ${{ parameters.image_type }} `
                        -ResourceGroup $(AZURE_RESOURCE_GROUP) `
                        -StorageAccount $(AZURE_STORAGE_ACCOUNT) `
                        -SubscriptionId $(AZURE_SUBSCRIPTION) `
                        -TenantId $(AZURE_TENANT) `
                        -Location $(AZURE_LOCATION) `
                        -VirtualNetworkName $(BUILD_AGENT_VNET_NAME) `
                        -VirtualNetworkRG $(BUILD_AGENT_VNET_RESOURCE_GROUP) `
                        -VirtualNetworkSubnet $(BUILD_AGENT_SUBNET_NAME) `
                        -GitHubFeedToken $(GITHUB_TOKEN)
    displayName: Build VM

  - script: |
      ./images.CI/cleanup.ps1 -ResourcesNamePrefix $(Build.BuildNumber) `
                     -ClientId $(CLIENT_ID) `
                     -ClientSecret $(CLIENT_SECRET) `
                     -Image ${{ parameters.image_type }} `
                     -SubscriptionId $(AZURE_SUBSCRIPTION) `
                     -TenantId $(AZURE_TENANT)
    displayName: Clean up resources
    condition: always()