# schedules:
# - cron: "0 0 * * *"
#   displayName: Daily
#   branches:
#     include:
#     - master
#   always: true

variables:
- group: "Image Generation Variables"

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- template: image-generation.yml
  parameters:
    image_type: ubuntu1604