name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 3 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not had any activity in 30 days, if you still require assistance please remove the `no-issue-activity` label'
        stale-issue-label: 'no-issue-activity'
        days-before-stale: 30
        days-before-close: 14
